using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Shop.Core.Entities
{
    public class CustomerBasket
    {
        //id is generated by client (angular app)
        public string Id { get; set; }
        public List<BasketItem> Items { get; set; } = new();
        
        //optional, cuz when adding to basket, user won't be able to select dm until he gets to checkout
        public int? DeliveryMethodId { get; set; }
        public string ClientSecret { get; set; }
        public string PaymentIntentId { get; set; }
        public CustomerBasket(string id)
        {
            Id = id;
        }

        public CustomerBasket()
        {

        }
    }
}
